In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [5]:
arr = np.append(arr, 6)
arr

array([1, 2, 3, 4, 5, 6])

In [8]:
arr = np.insert(arr, 2, [1, 2, 4])
arr

array([1, 2, 1, 2, 4, 1, 2, 4, 3, 4, 5, 6])

In [15]:
arr2 = np.delete(arr, [0, 1,2,3,4])
arr2

array([4, 3, 4, 5, 6])

In [16]:
## How todelete in cells

In [17]:
# Copying an array

In [18]:
arr2= np.array([4, 5, 6, 7, 8])

In [20]:
arr3 = arr2.copy()
arr3

array([4, 5, 6, 7, 8])

In [25]:
arr1 = np.array([[1, 2, 3], [1, 2, 3]])
arr4 = np.array([[4, 5, 6],[4, 5, 6]])
arr_cat = np.concatenate((arr1, arr4), axis = 0)
arr_cat

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [29]:
catV = np.vstack((arr1, arr4))
catV

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [31]:
catH = np.hstack((arr1, arr4))
catH

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [41]:
array = np.random.randint(1, 10, 10)
array

array([2, 2, 4, 7, 7, 8, 5, 3, 5, 6])

In [56]:
np.unique(array, return_counts = True)

(array([2, 3, 4, 5, 6, 7, 8]), array([2, 1, 1, 2, 1, 2, 1], dtype=int64))

In [58]:
array2 = np.random.randint(1, 10, 10)
print(np.intersect1d(array, array2))
print(np.union1d(array,array2))
print(np.setdiff1d(array, array2))
print(np.setxor1d(array, array2))

[2 3 4 5 8]
[1 2 3 4 5 6 7 8 9]
[6 7]
[1 6 7 9]
